magic_quotes_gpc = Off
magic_quotes_runtime = Off
magic_quotes_sybase = Off
[Date]
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = America/New_York